# Generated by Django 5.0 on 2023-12-11 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGFood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_binh_luan_cha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGFood.binhluan')),
                ('id_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGFood.taikhoan')),
            ],
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem', models.IntegerField()),
                ('id_cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cua_hang_duoc_danh_gia', to='SGFood.taikhoan')),
                ('id_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_cua_nguoi_dung', to='SGFood.taikhoan')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cua_hang_follow', to='SGFood.taikhoan')),
                ('id_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_dung_follow', to='SGFood.taikhoan')),
            ],
        ),
        migrations.CreateModel(
            name='TimKiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon_an', models.CharField(default=' ', max_length=50, null=True)),
                ('gia', models.IntegerField(default=' ', null=True)),
                ('ten_loai_thuc_an', models.CharField(default=' ', max_length=50, null=True)),
                ('ten_cua_hang', models.CharField(default=' ', max_length=50, null=True)),
                ('id_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGFood.taikhoan')),
            ],
        ),
    ]
