# Generated by Django 5.0 on 2023-12-11 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGFood', '0002_binhluan_danhgia_follow_timkiem'),
    ]

    operations = [
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_san_pham', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoaiThucAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai_thuc_an', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ThoiDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayTao', models.DateTimeField(auto_now_add=True)),
                ('id_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGFood.taikhoan')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('don_gia', models.IntegerField()),
                ('id_hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGFood.hoadon')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('id_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGFood.taikhoan')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGFood.menu')),
            ],
        ),
        migrations.CreateModel(
            name='MonAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon_an', models.CharField(max_length=50, null=True)),
                ('gia', models.IntegerField(null=True)),
                ('trai_thai', models.BooleanField(default=False)),
                ('hinh_anh', models.ImageField(upload_to='monan/%Y/%m/%d')),
                ('so_luong', models.IntegerField()),
                ('id_don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGFood.hoadon')),
                ('id_gio_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGFood.giohang')),
                ('id_loai_thuc_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGFood.loaithucan')),
                ('id_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGFood.taikhoan')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='danh_sach_mon_an',
            field=models.ManyToManyField(through='SGFood.ChiTietMenu', to='SGFood.monan'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='mon_an',
            field=models.ManyToManyField(through='SGFood.ChiTietHoaDon', to='SGFood.monan'),
        ),
        migrations.AddField(
            model_name='chitietmenu',
            name='id_mon_an',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGFood.monan'),
        ),
        migrations.AddField(
            model_name='chitiethoadon',
            name='id_mon_an',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGFood.monan'),
        ),
        migrations.CreateModel(
            name='ThoiGianBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mon_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGFood.monan')),
                ('id_thoi_diem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGFood.thoidiem')),
            ],
        ),
        migrations.AddField(
            model_name='thoidiem',
            name='mon_an',
            field=models.ManyToManyField(through='SGFood.ThoiGianBan', to='SGFood.monan'),
        ),
    ]
